# Connect to DB

In [ ]:
# =============================================================================
# drop and recreate the sqlite database and bchusdt_1m table (composite pk)
# =============================================================================
import os
import sqlite3
import subprocess
import json
import utils as utils
import pandas as pd

# =============================================================================
# database path and table name
# =============================================================================
cfg          = utils._load_config()
DB_PATH      = cfg["database"]["db_path"]
print(DB_PATH)

D:/repos/chronoquant/data/bchusdt_data.db

# Select the tables

In [ ]:
conn   = sqlite3.connect(DB_PATH)
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
conn.close()
print(tables)

             name
0      bchusdt_1m
1  bchusdt_1m_dev

# Select the data from BCHUSDT 1m table

In [ ]:
# Adatbázis kapcsolat létrehozásaq
conn = sqlite3.connect(DB_PATH)
df   = pd.read_sql_query("SELECT * FROM bchusdt_1m;", conn)
conn.close()
df.head()

    open_time_ms         open_time    open    high     low   close    volume
0  1574935200000  2019-11-28 12:00  220.08  224.60  212.02  224.60   7.23587
1  1574935260000  2019-11-28 12:01  224.60  224.60  224.59  224.59   1.75804
2  1574935320000  2019-11-28 12:02  224.59  224.60  218.50  218.67  12.24359
3  1574935380000  2019-11-28 12:03  219.00  222.53  219.00  219.06  14.87814
4  1574935440000  2019-11-28 12:04  220.00  223.89  218.52  223.89  61.79853

# Select the data from BCHUSDT 1m DEV table

In [4]:
conn = sqlite3.connect(DB_PATH)
df   = pd.read_sql_query("SELECT * FROM bchusdt_1m_dev;", conn)
conn.close()
df.head()

,open_time,close,rolling_max,ratio,spike_flag,rsi_backward_14,roc_14,roc_140,macd_diff,sma_ratio_14,sma_ratio_140,bb_width_14,bb_width_140
0,2019-11-28 12:00:00,224.60,224.60,1.000000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-11-28 12:01:00,224.59,224.59,1.000000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-11-28 12:02:00,218.67,223.89,1.023872,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-11-28 12:03:00,219.06,223.89,1.022049,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-11-28 12:04:00,223.89,223.89,1.000000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Drop table

In [18]:
import sqlite3

conn = sqlite3.connect(DB_PATH)
conn.execute("DROP TABLE IF EXISTS bchusdt_1m_dev;")
conn.commit()
conn.close()