# Connect to DB

In [1]:
# =============================================================================
# drop and recreate the sqlite database and bchusdt_1m table (composite pk)
# =============================================================================
import os
import sqlite3
import subprocess
import json
import utils as utils
import pandas as pd

# =============================================================================
# database path and table name
# =============================================================================
cfg          = utils._load_config()
DB_PATH      = cfg["database"]["db_path"]
print(DB_PATH)

D:/repos/chronoquant/data/bchusdt_data.db

# Create base table

In [4]:
#!/usr/bin/env python3
"""
Egyszerű script, ami létrehozza a data/ mappában a bchusdt_data.db SQLite fájlt.
Használat:
    python create_bchusdt_db.py
"""
from pathlib import Path
import sqlite3

def create_sqlite_file(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)  # létrehozza a data/ mappát, ha nincs
    # A sqlite3.connect létrehozza az .db fájlt, ha nem létezik
    conn = sqlite3.connect(str(path))
    conn.close()
    return path

if __name__ == "__main__":
    db_path = Path("data") / "bchusdt_data.db"
    created = create_sqlite_file(db_path)
    print(f"Létrehozva: {created.resolve()}")

Létrehozva: C:\repos\ChronoQuant\data\bchusdt_data.db

In [8]:
import database_codes.bch_usdt_1m as bhc_usd_1m
bhc_usd_1m.create_bchusdt_1m("config.json")

removed existing database file: C:/repos/chronoquant/data/bchusdt_data.db
created table 'bchusdt_1m' in database: C:/repos/chronoquant/data/bchusdt_data.db

# Select the tables

In [2]:
conn   = sqlite3.connect(DB_PATH)
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
conn.close()
print(tables)

             name
0      bchusdt_1m
1  bchusdt_1m_dev

# Select the data from BCHUSDT 1m table

In [8]:
# Adatbázis kapcsolat létrehozásaq
conn = sqlite3.connect(DB_PATH)
df   = pd.read_sql_query("SELECT * FROM bchusdt_1m;", conn)
conn.close()
df.tail(5)

,open_time_ms,open_time,open,high,low,close,volume
3109873,1761668400000,2025-10-28 16:20:00,563.3,563.3,562.8,562.8,0.342
3109874,1761668460000,2025-10-28 16:21:00,562.5,562.8,562.5,562.7,2.755
3109875,1761668520000,2025-10-28 16:22:00,562.5,562.5,562.5,562.5,0.000
3109876,1761668580000,2025-10-28 16:23:00,562.0,562.0,562.0,562.0,0.000
3109877,1761668640000,2025-10-28 16:24:00,561.6,561.6,561.6,561.6,0.000

# Select the data from BCHUSDT 1m DEV table

In [9]:
conn = sqlite3.connect(DB_PATH)
df   = pd.read_sql_query("SELECT * FROM bchusdt_1m_dev;", conn)
conn.close()
df.tail(5)

,open_time,close,rolling_max,ratio,spike_flag,feat_rsi_backward_14,feat_roc_14,feat_roc_140,feat_macd_diff,feat_sma_ratio_14,feat_sma_ratio_140,feat_bb_width_14,feat_bb_width_140
3109873,2025-10-28 16:20:00,562.8,562.8,1.0,0,50.938582,0.000000,-0.530223,-0.049095,0.999353,0.997464,0.357772,1.978607
3109874,2025-10-28 16:21:00,562.7,562.7,1.0,0,49.861279,0.017775,-0.424704,-0.090717,0.999163,0.997317,0.352513,1.980070
3109875,2025-10-28 16:22:00,562.5,562.5,1.0,0,47.688960,0.000000,-0.407224,-0.128700,0.998808,0.996992,0.352513,1.982442
3109876,2025-10-28 16:23:00,562.0,562.0,1.0,0,42.682459,-0.106648,-0.566171,-0.181263,0.997996,0.996146,0.401303,1.985914
3109877,2025-10-28 16:24:00,561.6,561.6,1.0,0,39.142190,-0.177746,-0.742312,-0.233415,0.997412,0.995490,0.482356,1.989505

# Drop table

In [1]:
import database_codes.bch_usdt_1m as bch_1m
bch_1m.create_bchusdt_1m(config_path="config.json")

removed existing database file: D:/repos/chronoquant/data/bchusdt_data.db
created table 'bchusdt_1m' in database: D:/repos/chronoquant/data/bchusdt_data.db

In [26]:
import sqlite3

conn = sqlite3.connect(DB_PATH)
conn.execute("DROP TABLE IF EXISTS bchusdt_1m_dev;")
conn.commit()
conn.close()

# create DEV data table with features

In [ ]:
import database_codes.bch_usdt_1m_dev as bch_1m_dev
import importlib
importlib.reload(bch_1m_dev)

open_time_from = "2021-01-01 00:00:00"
open_time_to   = "2021-01-01 00:01:00"

bch_1m_dev.create_dev_data_table(open_time_from, open_time_to)

Appended 2 rows into 'bchusdt_1m_dev' in DB 'D:/repos/chronoquant/data/bchusdt_data.db' for interval 2021-01-01 00:00:00 to 2021-01-01 00:01:00.

In [19]:
conn = sqlite3.connect(DB_PATH)
df   = pd.read_sql_query("SELECT * FROM bchusdt_1m_dev;", conn)
conn.close()
df.head(5)

,open_time,close,rolling_max,ratio,spike_flag,feat_rsi_backward_14,feat_roc_14,feat_roc_140,feat_macd_diff,feat_sma_ratio_14,feat_sma_ratio_140,feat_bb_width_14,feat_bb_width_140
0,2021-01-01 00:00:00,343.20,343.20,1.0,0,56.106183,-0.008740,0.186829,-0.034443,1.001021,1.003588,0.464630,0.866989
1,2021-01-01 00:01:00,343.19,343.19,1.0,0,55.951617,0.043727,0.221943,-0.011432,1.000960,1.003543,0.472695,0.874093

# model data test

In [19]:
import sqlite3

conn = sqlite3.connect(DB_PATH)
conn.execute("DROP TABLE IF EXISTS bch_usdt_1m_logreg_base;")
conn.commit()
conn.close()

In [20]:
# Example caller for create_logreg_base
# Sets two open_time bounds and calls the function to build/append the dataset.

import database_codes.bch_usdt_1m_logreg_base  as logreg
import importlib
importlib.reload(logreg)

from_open_time = "2025-10-28 00:00:00"
to_open_time   = "2025-10-28 01:00:00"

# Call the function to query dev table and append results to the final table
logreg.create_logreg_base(from_open_time, to_open_time)

Appended 61 rows to 'bch_usdt_1m_logreg_base' (from 2025-10-28 00:00:00 to 2025-10-28 01:00:00).

In [21]:
conn = sqlite3.connect(DB_PATH)
df   = pd.read_sql_query("SELECT * FROM bch_usdt_1m_logreg_base;", conn)
conn.close()
df.head(5)

,open_time,feat_rsi_backward_14,feat_roc_14,feat_roc_140,feat_sma_ratio_14,feat_bb_width_14,feat_bb_width_140,spike_flag,target_prob
0,2025-10-28 00:00:00,37.876357,-0.161754,-0.358744,0.999101,0.184423,0.831518,0,0.056110
1,2025-10-28 00:01:00,29.421489,-0.251663,-0.412778,0.998201,0.265079,0.832706,0,0.056499
2,2025-10-28 00:02:00,28.288108,-0.287563,-0.305481,0.998226,0.314720,0.836485,0,0.057869
3,2025-10-28 00:03:00,28.288108,-0.269639,-0.412852,0.998419,0.345415,0.838391,0,0.058641
4,2025-10-28 00:04:00,31.354940,-0.233729,-0.305426,0.998766,0.356733,0.841185,0,0.059935

# Time Test

In [9]:
from datetime        import datetime, timedelta

datetime.now()

datetime.datetime(2025, 10, 29, 8, 1, 35, 395887)

In [10]:
from datetime import datetime, timezone

now_utc = datetime.now(timezone.utc)        # aware datetime in UTC
print(now_utc)                              # e.g. 2025-10-29 07:20:07+00:00
print(now_utc.strftime("%Y-%m-%d %H:%M:%S"))# e.g. 2025-10-29 07:20:07   (UTC)
print(now_utc.isoformat())                  # e.g. 2025-10-29T07:20:07+00:00
# If you want the ISO string with "Z" for UTC:
print(now_utc.strftime("%Y-%m-%dT%H:%M:%SZ"))

2025-10-29 07:20:20.383032+00:00
2025-10-29 07:20:20
2025-10-29T07:20:20.383032+00:00
2025-10-29T07:20:20Z